#! /bin/bash

source "$HOME/bin/core/lsr.core.sh"

LSR_SET_COMMAND "gitlog"

LSR_SET_SUBCOMMAND "list"
LSR_DESCRIBE_SUBCOMMAND "list" "List 10 of the previous commits in current repo"

LSR_HANDLE_COMMAND "${LSR_PARSED_ARGUMENTS[@]}"
exit 0