#!/bin/bash
source "$HOME/projects/lsr_core/lsr.core.io.sh"
source "$HOME/projects/lsr_core/lsr.core.commands.sh"
source "$HOME/projects/lsr_core/lsr.core.table.sh"
source "$HOME/projects/lsr_core/lsr.core.cli.sh"

if [[ ! -f "$HOME/projects/projects.json" ]]; then
    print_error "~/projects/projects.json does not exist"
    exit
fi

if [[ ! -f "$HOME/projects/demos.json" ]]; then
    print_error "~/projects/demos.json does not exist"
    exit
fi

if has_flag "--date" "$@"; then
    title=$(get_flag_value "--title" "$@")
    echo "Title given: '$title'"
else
    echo "No title given"
fi

